services:
  backend:
    build: ./BackEnd
    container_name: backend

    ports:
      - "8000:8000"

    environment:
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}

  frontend:
    build:
      context: ./FrontEnd
      args:
        API_BASE_URL: ${API_BASE_URL}

    container_name: frontend

    ports:
      - "3000:3000"

    depends_on:
      - backend